export enum STATUS {
    AVAILABLE = 'AVAILABLE',
    OCCUPIEDP1 = 'OCCUPIEDP1',
    OCCUPIEDP2 = 'OCCUPIEDP2',
    SELECTED = 'SELECTED'
}

export enum PLAYERTURN {
    PLAYER1 = 'PLAYER1',
    PLAYER2 = 'PLAYER2'
}